### ISSUE TITLE
Improve error handling of build in commands

### ISSUE THREAD

**Issue by SpyrosRoum** [G000D1ESS/snakeshell#1]
Hello, nice project but it has some rough edges (understandably). I'm very used to `cd` by itself meaning `cd ~`, but when I tried that on snakeshell I got `IndexError: list index out of range` and the shell exited.
  
Even if cd to home is not the default behavior, missing arguments should not make it crash completely.

**Comment by G000D1ESS** [comment]
Hello!
Thank you very much for the feedback! You’re right — cd without arguments is a very common command, but I somehow overlooked this behavior. I’ll fix the issue and add a couple of tests to cover this case.

I’ll also review and fix other built-in commands to ensure they don’t face similar issues and prevent any crashes!

**Comment by G000D1ESS** [comment]
Thanks again for the feedback!

I’ve fixed the issue. The shell is now more stable, and I’ve added error messages for the built-in commands:
- `cd` now goes to the home directory if no arguments are provided.
- Errors for missing or invalid arguments no longer cause the shell to crash.

Let me know if you find any other problems!
